# Lance MongoDB en une commande (il faut Docker) : docker compose up -d
services:
  mongo:
    image: mongo:7
    container_name: marketplace-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
